Microsys
openil/sja1105-tool pull request #29
Opened 2018-10-12 07:58 UTC by Kay-Potthoff

Compiled and ported sja1105-tool on LS1046. The fixes are necessary, because the tool terminated
with segmentation fault or occasionally with 'unmap: invalid pointer'.

2018-10-12 10:27 UTC, vladimiroltean requested changes
I don't think this is really correct. You shouldn't abuse the FREE macro by deliberately leaving two free() loops in the same code path.

2018-10-12 10:28 UTC, vladimiroltean requested changes
Indentation, spacing.

2018-10-16 09:05 UTC, Kay-Potthoff commented
Hi,
as you suggested I have removed the macro FREE() and replaced it with explicit calls of free().
Additionally, I fixed the problems that in some error cases allocated resources have not been freed
correctly.
-Kay

2018-10-16 16:35 UTC, vladimiroltean commented
Do you mind if I make changes to your patchset?
There are still things that need to change:
* Squash the addition of the FREE() macro with its removal.
* The `staging-area.c: fixed memory errors` patch is duplicating some cleanup code instead of fixing the error codepath. If you're fixing it you might as well do it properly.
* Patch `parse-status.c: fixed memory error in status_ports()` is still using calloc memory without NULL-checking it.
* Some NULL checks are mindless e.g. `main.c: replaced FREE() macro` where you end up checking `if (spi_setup->staging_area)` twice. There are other places as well.

2022-11-18 08:00 UTC, closed without merging